#DO NOT TOCH IT !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#iT IS ALL GENERATED BY A STUPID AI!


import networkx as nx
import matplotlib.pyplot as plt


from collections import deque



def maze_to_tree_graph1(maze):
    if not maze:
        return

    rows = len(maze)
    cols = len(maze[0]) if rows else 0

    walkable_cells = []
    for y in range(1, rows - 1, 2):
        for x in range(1, cols - 1, 2):
            value = maze[y][x]
            if value in (0, 2):
                walkable_cells.append((x, y))

    if not walkable_cells:
        return

    start = (1,1)


    graph = nx.Graph()
    for x, y in walkable_cells:
        graph.add_node((x, y))

    for x, y in walkable_cells:
        node = (x, y)
        if x + 2 < cols and maze[y][x + 1] == 0 and (x + 2, y) in graph:
            graph.add_edge(node, (x + 2, y))
        if y + 2 < rows and maze[y + 1][x] == 0 and (x, y + 2) in graph:
            graph.add_edge(node, (x, y + 2))

    if not nx.is_tree(graph):
        return

    root = start
    parent_map = {root: None}
    children_map = {root: []}
    stack = [root]

    while stack:
        node = stack.pop()
        for neighbor in graph.neighbors(node):
            if neighbor == parent_map[node]:
                continue
            if neighbor in parent_map:
                continue
            parent_map[neighbor] = node
            children_map.setdefault(neighbor, [])
            children_map[node].append(neighbor)
            stack.append(neighbor)

    subtree_sizes = {}

    def compute_subtree_size(node):
        size = 1
        for child in children_map.get(node, []):
            size += compute_subtree_size(child)
        subtree_sizes[node] = size
        return size

    compute_subtree_size(root)

    positions = {}
    level_gap = 1.8
    sibling_gap = 1.2
    

    def place_subtree(node, depth, parent_x):
        children = children_map.get(node, [])
        if not children:
            positions[node] = (parent_x, -depth * level_gap)
            return

        total_weight = sum(subtree_sizes[child] for child in children)
        start_x = parent_x - (total_weight * sibling_gap) / 2.0
        cursor_x = start_x

        for child in children:
            child_weight = subtree_sizes[child]
            child_x = cursor_x + (child_weight * sibling_gap) / 2.0
            positions[child] = (child_x, -(depth + 1) * level_gap)
            place_subtree(child, depth + 1, child_x)
            cursor_x += child_weight * sibling_gap


        

    positions[root] = (0.0, 0.0)
    place_subtree(root, 0, 0.0)

    labels = {}

    end = (cols - 2, rows - 2)
    for node in graph.nodes:
        if node == root:
            labels[node] = "Start"
        elif node == end:
            labels[node] = "End"
        else:
            labels[node] = f"({node[0]}, {node[1]})"
            #pass
    
    fig, ax = plt.subplots(figsize=(10, 10))
    nx.draw_networkx(
        graph,
        pos=positions,
        labels=labels,
        with_labels=True,
        node_size=10,
        #node_color="#dbeafe",
        node_color="#dbeafe",
        edge_color="#374151",
        linewidths=1.2,
        font_size=9,
        font_weight="bold",
        arrows=False,
    )

    ax.set_aspect("equal")
    ax.axis("off")
    plt.tight_layout()
    plt.show(block=False)
    plt.pause(0.001)

def maze_to_tree_graph2(maze):
    if not maze:
        return

    rows = len(maze)
    cols = len(maze[0]) if rows else 0

    walkable_cells = []
    for y in range(1, rows - 1, 2):
        for x in range(1, cols - 1, 2):
            value = maze[y][x]
            if value in (0, 2):
                walkable_cells.append((x, y))

    if not walkable_cells:
        return

    start = (1,1)

    graph = nx.Graph()
    for x, y in walkable_cells:
        graph.add_node((x, y))

    for x, y in walkable_cells:
        node = (x, y)
        if x + 2 < cols and maze[y][x + 1] == 0 and (x + 2, y) in graph:
            graph.add_edge(node, (x + 2, y))
        if y + 2 < rows and maze[y + 1][x] == 0 and (x, y + 2) in graph:
            graph.add_edge(node, (x, y + 2))

    if not nx.is_tree(graph):
        return

    root = start
    parent_map = {root: None}
    children_map = {root: []}
    stack = [root]

    while stack:
        node = stack.pop()
        for neighbor in graph.neighbors(node):
            if neighbor == parent_map[node]:
                continue
            if neighbor in parent_map:
                continue
            parent_map[neighbor] = node
            children_map.setdefault(neighbor, [])
            children_map[node].append(neighbor)
            stack.append(neighbor)

    subtree_sizes = {}

    def compute_subtree_size(node):
        size = 1
        for child in children_map.get(node, []):
            size += compute_subtree_size(child)
        subtree_sizes[node] = size
        return size

    compute_subtree_size(root)

    positions = {}
    level_gap = 1.8
    sibling_gap = 1.2
    

    def place_subtree(node, depth, parent_x):
        children = children_map.get(node, [])
        if not children:
            positions[node] = (parent_x, -depth * level_gap)
            return

        total_weight = sum(subtree_sizes[child] for child in children)
        start_x = parent_x - (total_weight * sibling_gap) / 2.0
        cursor_x = start_x


        weights = [subtree_sizes[c] for c in children]

        total_weight = sum(weights)

        cursor_x = parent_x - total_weight * sibling_gap / 2

        child_centers = []

        for w in weights:
            center = cursor_x + w * sibling_gap / 2
            child_centers.append(center)
            cursor_x += w * sibling_gap

        # 计算孩子中心的中点
        mid = (child_centers[0] + child_centers[-1]) / 2

        # 计算需要整体平移多少
        offset = parent_x - mid

        for child, child_x, w in zip(children, child_centers, weights):
            child_x += offset
            positions[child] = (child_x, -(depth + 1) * level_gap)
            place_subtree(child, depth + 1, child_x)
        

    positions[root] = (0.0, 0.0)
    place_subtree(root, 0, 0.0)

    labels = {}

    end = (cols - 2, rows - 2)
    for node in graph.nodes:
        if node == root:
            labels[node] = "Start"
        elif node == end:
            labels[node] = "End"
        else:
            #labels[node] = f"({node[0]}, {node[1]})"
            pass
    
    fig, ax = plt.subplots(figsize=(10, 10))
    nx.draw_networkx(
        graph,
        pos=positions,
        labels=labels,
        with_labels=True,
        node_size=10,
        #node_color="#dbeafe",
        node_color="#dbeafe",
        edge_color="#374151",
        linewidths=1.2,
        font_size=9,
        font_weight="bold",
        arrows=False,
    )

    ax.set_aspect("equal")
    ax.axis("off")
    plt.tight_layout()
    plt.show()



def maze_to_tree_graph3(maze):
    G = nx.Graph()

    size = len(maze) // 2

    # 建图
    G.add_edge("Start", (0, 0))
    G.add_edge((size - 1, size - 1), "End")

    for y in range(size):
        grid_y = y * 2 + 1

        for x in range(size):
            grid_x = x * 2 + 1

            if x != 0 and maze[grid_y][grid_x - 1] == 0:
                G.add_edge((x, y), (x - 1, y))

            if y != 0 and maze[grid_y - 1][grid_x] == 0:
                G.add_edge((x, y), (x, y - 1))

    # ---------- BFS ----------
    depth = {"Start": 0}
    queue = deque(["Start"])

    while queue:
        node = queue.popleft()

        for nxt in G.neighbors(node):
            if nxt not in depth:
                depth[nxt] = depth[node] + 1
                queue.append(nxt)

    # ---------- 每层有哪些节点 ----------
    levels = {}

    for node, d in depth.items():
        levels.setdefault(d, []).append(node)

    # ---------- 自动计算坐标 ----------
    pos = {}

    vertical_gap = 2.5
    horizontal_gap = 2.0

    max_width = max(len(v) for v in levels.values())

    for d in sorted(levels.keys()):

        nodes = levels[d]
        n = len(nodes)

        total_width = (n - 1) * horizontal_gap

        start_x = -total_width / 2

        for i, node in enumerate(nodes):

            x = start_x + i * horizontal_gap

            y = -d * vertical_gap

            pos[node] = (x, y)

    # ---------- 畫圖 ----------
    plt.figure(figsize=(10, 10))

    nx.draw(
        G,
        pos,
        with_labels=True,
        node_size=500,
        node_color="lightblue",
        edgecolors="black",
        font_size=8
    )

    plt.axis("equal")
    plt.axis("off")

    print("Nodes:", G.number_of_nodes())
    print("Edges:", G.number_of_edges())
    plt.show()
'''
    plt.show(block=False)
    plt.pause(0.001)'''